name: Build Binaries for Linux64

on:
  push:
    branches: [ experiments-with-ghactions ]
  pull_request:
    branches: [ experiments-with-ghactions ]

jobs:
  wtfisthis:
    name: Path lister
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - uses: actions/checkout@v1

      - name: Fetch action
        id: pl
        uses: Rishabh510/Path-lister-action@master
        with:
          path: "./"
          type: ".txt"

      - name: Output results
        run: |
          echo "Found ${{ steps.pl.outputs.path_count }} file(s) with this extension:"
          for i in ${{ steps.pl.outputs.paths }}; do
          echo $i
          done
    
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ashutoshvarma/action-cmake-build@master
        with:
          source-dir: ${{ runner.workspace }}/../
          build-dir: ${{ runner.workspace }}/LinuxBuild
          # will set the CC & CXX for cmake
          cc: gcc
          cxx: g++
          build-type: Release
          # Extra options pass to cmake while configuring project
          # configure-options:
          run-test: false
          # ctest-options: -R mytest
          # install the build using cmake --install
          # install-build: true
          # run build using '-j [parallel]' to use multiple threads to build
          # parallel: 
