name: Build for Linux 64bit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    build_release_linux64:
        name: Linux 64Bit (Release)
        runs-on: ubuntu-latest
        steps:
        
        - uses: actions/checkout@v2
        
        - name: Run CMake to configure and create a Release build
          uses: ashutoshvarma/action-cmake-build@master
          with:
            build-dir: ${{ runner.workspace }}/build
            cc: gcc
            cxx: g++
            build-type: Release
            configure-options: -DENET_DEBUG=OFF

        - name: Upload release build artifact
          uses: actions/upload-artifact@v2
          with:
            name: Linux64-Release-Binary
            path: ${{ runner.workspace }}/build/libenet.so
            
    build_debug_linux64:
        name: Linux 64Bit (Debug)
        runs-on: ubuntu-latest
        steps:
        
        - uses: actions/checkout@v2
        
        - name: Run CMake to configure and create a Debug build.
          uses: ashutoshvarma/action-cmake-build@master
          with:
            build-dir: ${{ runner.workspace }}/build
            cc: gcc
            cxx: g++
            build-type: Debug
            configure-options: -DENET_DEBUG=ON

        - name: Upload debug build artifact
          uses: actions/upload-artifact@v2
          with:
            name: Linux64-Debug-Binary
            path: ${{ runner.workspace }}/build/libenet.so